#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:15:00
#PBS -N FSLBET
#PBS -V

if [ $ENV == "IUHPC" ]; then
    module load fsl
fi

export dwi=$(jq -r .dwi config.json)
export bvals=$(jq -r .bvals config.json)
export bvecs=$(jq -r .bvecs config.json)
export fthresh=$(jq -r .fthreshold config.json)
export gthresh=$(jq -r .gthreshold config.json)

cp ${dwi} dwi_original.nii.gz;
cp ${bvals} dwi.bvals;
cp ${bvecs} dwi.bvecs;

select_dwi_vols \
    dwi_original.nii.gz \
    ${bvals} \
    nodif.nii.gz \
    0;
    
fslmaths nodif \
    -Tmean \
    nodif_mean;

# Brain extraction before alignment
bet nodif_mean.nii.gz \
    dwi \
    -f $fthresh \
    -g $gthresh \
    -m;

mv dwi_mask.nii.gz mask.nii.gz;
rm -rf nodif.nii.gz nodif_mean.nii.gz dwi_original.nii.gz

