#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=0:10:00
#PBS -N FSLBET

set -x

export input=$(jq -r .input config.json)
export fthresh=$(jq -r .fthreshold config.json)

singularity exec -e docker://brainlife/fsl:5.0.9 bet $input masked.nii.gz -m -f $fthresh

mkdir -p mask
cp masked_mask.nii.gz mask/mask.nii.gz
